version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
      - image: arangodb:3.4.7
        environment:
          ARANGO_ROOT_PASSWORD: gruff_test
    working_directory: /go/src/github.com/GruffDebate/server

    environment:
      TEST_RESULTS: /tmp/test-results
    
    steps: 
      - checkout 
      - run: mkdir -p $TEST_RESULTS 

      - restore_cache:
        keys:
          - v1-pkg-cache

      - run:
          name: Waiting for Aragondb to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 8529 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Aragondb && exit 1
