apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: default
  labels:
    app: server
spec:
  revisionHistoryLimit: 5
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: gruffdebate/server:$COMMIT_SHA1
          env:
            - name: GRUFF_ENV
              value: "production"
            - name: ARANGO_ENDPOINT
              value: "http://67.207.87.34:8529"
            - name: ARANGO_USER
              value: "root"
            - name: ARANGO_PASS
              value: "ha2WF4qdHc"
          ports:
            - containerPort: 8080